version: "3.5"

services:
  web:
    container_name: pmid-pdf-api-prod
    environment:
      - FM_ENV_CONFIG=production
      - PYTHONUNBUFFERED=1
    command: sh /app/dockerfiles/sh/run_gunicorn.sh 8091
    ports:
      - "8091:8091"
